ARG version
FROM almalinux:${version-9}
ARG course="docker" \
    stdname="vinod" \
    duration="10hrs"
ENV course=${course} \
    name=${stdname} \
    duration=${duration}
RUN echo "Course is: ${course}, name: ${std-name}, duration: ${duration}"
CMD ["sleep", "100"]